config:
  MD013: false

ignores:
  - ".github"
  - "assets"
  - "**/.bash_profile"
  - "**.json"
  - "**.lua"
  - "**.yml"
  - "**.sh"
  - "**.toml"
  - "**.txt"
  - "**/*.dockerfile"
  - "**/node_modules"
