services:
  nvim:
    container_name: nvim-dev
    build:
      context: .
      dockerfile: nvim.dockerfile
    tty: true
    stdin_open: true
    command: ["sleep", "infinity"]
    restart: always
    networks:
      - my-nvim
    volumes:
      - ..:/workspace
networks:
  my-nvim:
    driver: bridge
    external: true
