name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read

jobs:
  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "25"

      - name: Install markdownlint-cli2
        run: npm install --no-save markdownlint-cli2

      - name: Run markdownlint-cli2
        run: npx markdownlint-cli2 "**/*.md"

  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "25"

      - name: Install prettier
        run: npm install --no-save prettier

      - name: Run prettier
        run: npx prettier --check .

  shell-lint:
    name: shell-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install shfmt
        run: go install mvdan.cc/sh/v3/cmd/shfmt@latest

      - name: Run shfmt
        run: shfmt -d .

      - name: Run shellcheck
        run: shellcheck ./**/*.sh
